if(x$(".page-members:has(DIV.banner-header.profileCoverArea)").length&&(x$(document).ready(function(){var c=x$('.aboutTab-questionAndAnswer P.aboutTab-answer:contains("{")').text();x$("body").append("<style>"+c+"</style>");x$('DIV.aboutTab-questionAndAnswer:contains("{")').hide()}),x$("DIV.aboutTab-questionAndAnswer:has(P.aboutTab-answer:contains('iframe'))").length)){if(x$(".cell_off").length&&1024<=screen.width){var GEOCOMhd=document.getElementsByTagName("body")[0],GEONodehd=document.createElement("link");
GEONodehd.type="text/css";GEONodehd.rel="stylesheet";GEONodehd.id="GEOPEM";GEONodehd.media="screen";GEOCOMhd.appendChild(GEONodehd);var GEOPM=document.getElementsByTagName("head")[0],GEOMODSP=document.createElement("link");GEOMODSP.type="text/css";GEOMODSP.rel="stylesheet";GEOMODSP.media="screen";GEOPM.appendChild(GEOMODSP);GEONodehd.href="http://api.ning.com/files/6Yi1*KCqJUR*B5L1xAYZ1OTqxJMzCAsVltsrTnrFCiK2DnTmEuxpFIGYiGvwbjyOpeeLM5LOiFSUFYYqelG6GTmzJ5c0P0Xs/default.css";GEOMODSP.href="http://api.ning.com:80/files/nkQiLxDRFQUHu3UTL2CKVJq61sTB*9K3PZF*hahqLZfHEh85pR3xCT9HzdmjgfZ9W934FbdPH7m4i8Nx*4*ix1pRdNBmEj*G/trophycase.css";
x$("UL.ningbar-userLinks.linkbar").before(x$("<button onclick=GEOswap('http://api.ning.com:80/files/aMeStxODW*jKXRzKNjgbVHJKg*b5F-plxJby4CNUWH0RCcnsqDRvIhajG8h2hYeA6Jo5otV*3WgPnCxSNE4exdxmFhxYcohx/n3MyembedGEOv2.5p2.css') id='mymv'></button>"))}x$(".cell_on").length&&(GEOCOMhd=document.getElementsByTagName("body")[0],GEONodehd=document.createElement("link"),GEONodehd.type="text/css",GEONodehd.rel="stylesheet",GEONodehd.id="GEOPEM",GEONodehd.media="screen",GEOCOMhd.appendChild(GEONodehd),GEOPM=document.getElementsByTagName("head")[0],
GEOMODSP=document.createElement("link"),GEOMODSP.type="text/css",GEOMODSP.rel="stylesheet",GEOMODSP.media="screen",GEOPM.appendChild(GEOMODSP),GEONodehd.href="http://api.ning.com/files/6Yi1*KCqJUR*B5L1xAYZ1OTqxJMzCAsVltsrTnrFCiK2DnTmEuxpFIGYiGvwbjyOpeeLM5LOiFSUFYYqelG6GTmzJ5c0P0Xs/default.css",GEOMODSP.href="http://api.ning.com:80/files/I*NXTuFuhJgef6cjS9wy9iQViKUQ-igZY*ZlT3VJKUC4ou5e9CJTvm4rj9yVnQvZlHIGetOZDiW6ClxtZNNkMPaH107Af6qv/n3_Myvid_v2.5_RT_p1an.css",x$("UL.ningbar-userLinks.linkbar").before(x$("<button onclick=GEOswap('http://api.ning.com:80/files/aMeStxODW*jKXRzKNjgbVHJKg*b5F-plxJby4CNUWH0RCcnsqDRvIhajG8h2hYeA6Jo5otV*3WgPnCxSNE4exdxmFhxYcohx/n3MyembedGEOv2.5p2.css') id='mymv'></button>")));
x$(document).ready(function(){1024<=screen.width&&x$(".cell_off").length&&(x$(".profileCoverArea-frame.cf:has(DIV.banner-header.profileCoverArea)").after('<div class="SP_Profile_Embed">'),b=x$('.aboutTab-questionAndAnswer P.aboutTab-answer:contains("iframe")').text(),x$(".SP_Profile_Embed").html(b),x$(".SP_Profile_Embed").contents().filter(function(){return 1!=this.nodeType}).remove(),x$("BODY").after(x$("<div class='geospembed_c'><button onclick=GEOswap('http://bit.ly/1Bs1unr') id='embed_close'>Close</button></div>")),
x$(".page-members:has(.central-content.cf SECTION.site-bodyFrame DIV.site-body.container DIV.banner-header.profileCoverArea) iframe").each(function(){var c=x$(this).attr("src");0<x$(this).attr("src").indexOf("?")?x$(this).attr({src:c+"&wmode=transparent",wmode:"Opaque"}):x$(this).attr({src:c+"?wmode=transparent",wmode:"Opaque"})}))});x$("#no_gf.cell_off").length&&(!function(c,d){"function"==typeof define&&define.amd?define(d):"object"==typeof exports?module.exports=d:c.fluidvids=d()}(this,function(){function c(c){return(new RegExp("^(https?:)?//(?:"+
d.players.join("|")+").*$","i")).test(c)}var d={selector:["iframe","object"],players:["www.youtube.com","player.vimeo.com","www.slideshare.net/"]},k=document.head||document.getElementsByTagName("head")[0];return d.render=function(){for(var l=document.querySelectorAll(d.selector.join()),f=l.length;f--;){var e=l[f];if((c(e.src)||c(e.data))&&!e.getAttribute("data-fluidvids")){var g=document.createElement("div");e.parentNode.insertBefore(g,e);e.className+=(e.className?" ":"")+"fluidvids-item";e.setAttribute("data-fluidvids",
"loaded");g.className+="fluidvids";var k=g.style,h;h=e.width;h=parseInt(e.height,10)/parseInt(h,10)*100+"%";k.paddingTop=h;g.appendChild(e)}}},d.init=function(c){for(var f in c)d[f]=c[f];d.render();c=document.createElement("div");c.innerHTML="<p>x</p><style>.fluidvids {width: 100%; max-width: 100%; position: relative;}.fluidvids-item {position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;}</style>";k.appendChild(c.childNodes[1])},d}),x$(document).ready(function(){fluidvids.init({selector:[".SP_Profile_Embed iframe",
".SP_Profile_Embed object"],players:["www.youtube.com","player.vimeo.com","www.slideshare.net/"]});x$(".SP_Profile_Embed .fluidvids").each(function(){var c=x$(this);c.add(c.nextUntil(".fluidvids")).wrapAll('<div class="gframew"></div>');x$(".gframew").css({"max-width":"95%",left:"0px",right:"0px","margin-left":"auto","margin-right":"auto","margin-bottom":"15px"})})}));x$(document).ready(function(){x$(".cell_on").length&&(x$(".profileCoverArea-frame.cf:has(DIV.banner-header.profileCoverArea)").after('<div class="SP_Profile_Embed">'),
a=x$('.aboutTab-questionAndAnswer P.aboutTab-answer:contains("iframe")').text(),x$(".SP_Profile_Embed").html(a),x$(".SP_Profile_Embed").contents().filter(function(){return 1!=this.nodeType}).remove(),x$("BODY").after(x$("<div class='geospembed_c'><button onclick=GEOswap('http://bit.ly/1Bs1unr') id='embed_close'>Close</button></div>")),x$(".page-members:has(.central-content.cf SECTION.site-bodyFrame DIV.site-body.container DIV.banner-header.profileCoverArea) iframe").each(function(){var c=x$(this).attr("src");
0<x$(this).attr("src").indexOf("?")?x$(this).attr({src:c+"&wmode=transparent",wmode:"Opaque"}):x$(this).attr({src:c+"?wmode=transparent",wmode:"Opaque"})}));x$('DIV.aboutTab-questionAndAnswer:contains("iframe")').remove()});x$("#no_gf.cell_on").length&&(!function(c,d){"function"==typeof define&&define.amd?define(d):"object"==typeof exports?module.exports=d:c.fluidvids=d()}(this,function(){function c(c){return(new RegExp("^(https?:)?//(?:"+d.players.join("|")+").*$","i")).test(c)}var d={selector:["iframe",
"object"],players:["www.youtube.com","player.vimeo.com","www.slideshare.net/"]},k=document.head||document.getElementsByTagName("head")[0];return d.render=function(){for(var l=document.querySelectorAll(d.selector.join()),f=l.length;f--;){var e=l[f];if((c(e.src)||c(e.data))&&!e.getAttribute("data-fluidvids")){var g=document.createElement("div");e.parentNode.insertBefore(g,e);e.className+=(e.className?" ":"")+"fluidvids-item";e.setAttribute("data-fluidvids","loaded");g.className+="fluidvids";var k=g.style,
h;h=e.width;h=parseInt(e.height,10)/parseInt(h,10)*100+"%";k.paddingTop=h;g.appendChild(e)}}},d.init=function(c){for(var f in c)d[f]=c[f];d.render();c=document.createElement("div");c.innerHTML="<p>x</p><style>.fluidvids {width: 100%; max-width: 100%; position: relative;}.fluidvids-item {position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;}</style>";k.appendChild(c.childNodes[1])},d}),x$(document).ready(function(){fluidvids.init({selector:[".SP_Profile_Embed iframe",".SP_Profile_Embed object"],
players:["www.youtube.com","player.vimeo.com","www.slideshare.net/"]});x$(".SP_Profile_Embed .fluidvids").each(function(){var c=x$(this);c.add(c.nextUntil(".fluidvids")).wrapAll('<div class="gframew"></div>');x$(".gframew").css({"max-width":"95%",left:"0px",right:"0px","margin-left":"auto","margin-right":"auto","margin-bottom":"15px"})})}))}
if(0<x$("#gframe").length){var addGeoStyleGF=function(c){var d=document.getElementById("geo_styles_jsGF");d||(d=document.createElement("style"),d.type="text/css",d.id="geo_styles_js",document.getElementsByTagName("body")[0].appendChild(d));d.appendChild(document.createTextNode(c))};!function(c,d){"function"==typeof define&&define.amd?define(d):"object"==typeof exports?module.exports=d:c.fluidvids=d()}(this,function(){function c(c){return(new RegExp("^(https?:)?//(?:"+d.players.join("|")+").*$","i")).test(c)}
var d={selector:["iframe","object"],players:["www.youtube.com","player.vimeo.com","www.slideshare.net/"]},k=document.head||document.getElementsByTagName("head")[0];return d.render=function(){for(var l=document.querySelectorAll(d.selector.join()),f=l.length;f--;){var e=l[f];if((c(e.src)||c(e.data))&&!e.getAttribute("data-fluidvids")){var g=document.createElement("div");e.parentNode.insertBefore(g,e);e.className+=(e.className?" ":"")+"fluidvids-item";e.setAttribute("data-fluidvids","loaded");g.className+=
"fluidvids";var k=g.style,h;h=e.width;h=parseInt(e.height,10)/parseInt(h,10)*100+"%";k.paddingTop=h;g.appendChild(e)}}},d.init=function(c){for(var f in c)d[f]=c[f];d.render();c=document.createElement("div");c.innerHTML="<p>x</p><style>.fluidvids {width: 100%; max-width: 100%; position: relative;}.fluidvids-item {position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;}</style>";k.appendChild(c.childNodes[1])},d});x$(document).ready(function(){fluidvids.init({selector:["iframe","object"],
players:["www.youtube.com","player.vimeo.com","www.slideshare.net/"]});x$(".fluidvids").each(function(){var c=x$(this);c.add(c.nextUntil(".fluidvids")).wrapAll('<div class="gframew"></div>');x$(".gframew").css({"max-width":"95%",left:"0px",right:"0px","margin-left":"auto","margin-right":"auto","margin-bottom":"15px"})});x$('.activityFeed-embed[data-type="video"], .activityFeed-embed[data-provider="SoundCloud"]').css({"max-width":"100%","max-height":"100%"});window.setInterval(function(){fluidvids.init({selector:[".comments-commentBody iframe",
".comments-commentBody object"],players:["www.youtube.com","player.vimeo.com","www.slideshare.net/"]})},3E3);window.setInterval(function(){fluidvids.init({selector:[".activityFeed-content iframe",".activityFeed-content object"],players:["www.youtube.com","player.vimeo.com","www.slideshare.net/"]})},3E3)});addGeoStyleGF('HTML BODY DIV.activityFeed-embed, .activityFeed-embed[data-type="video"] > .activityFeed-embedContent, .HTML activityFeed-embed[data-provider="SoundCloud"] > .activityFeed-embedContent { width: 100%!important; max-width: 100%!important; max-height: 100%!important;}HTML body .activityFeed-embed[data-type="video"] > .activityFeed-embedContent, HTML body .activityFeed-embed[data-provider="SoundCloud"] > .activityFeed-embedContent { width: 100%!important; height: auto!important; max-width: 100%!important; max-height: 100%!important; padding-bottom: 0%!important; position: relative!important;}')}
x$(document).ready(function(){x$('DIV.site-body.container-fixedFull.createProfilePage.profileQuestionForm.signInFlow DIV.profileQuestionForm div.form-field:contains("add CSS")').remove();x$('DIV.site-body.container-fixedFull.createProfilePage.profileQuestionForm.signInFlow DIV.profileQuestionForm div.form-field:contains("embed")').remove();x$('BODY.page-main.page-main-profilesettings.page-main-profilesettings-edit DIV.form-field:contains("embed") SPAN.input-prefix:contains("http://")').remove();x$('BODY.page-main.page-main-profilesettings.page-main-profilesettings-edit DIV.form-field:contains("embed") DIV.input.input-prefixed').css({width:"100%"})});
function GEOswap(c){document.getElementById("GEOPEM").setAttribute("href",c)};


/*! 
 * GEOCOM's "Embed Mod" RT v13.0 & gframe v11, JavaScript *
 * MOD for SweetPotato's "Profile Embed" *
 * & AnGellas Add CSS to Member Profiles *
 * George H. Compton IV *
 * george_compton@hotmail.com *
 * Date: may 17 6:00pm 2016 *
 * *********************************** 
 * ********************************** 
 * ********************************* 
 *   JavaScript #id & class calls *
 * id="no_gf" = MOD  " Fluid videos only in the mod DIV " 
 * id="gframe" = MOD + gframe v11.5, Fluid videos throughout your whole network *   
 * ************************************  
 * class="cell_on" or class="cell_off" 
 * will turn just the video MOD on or off for cell phones 1024px or smaller *
 * ************************************  
 * Change the "id" and "class" to "null" to only have the CSS feature enabled *
 */
